name: CI & Coverage - INPE

on:
  pull_request:
    branches: [ main ] # Dispara quando há PR para a main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
          
      - name: Instalar Dependências
        run: npm install
        
      - name: Rodar Testes com Cobertura
        run: npm run test:coverage # Executa o comando criado no Ex 1
        
      - name: Enviar Relatório para Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
